### ISSUE TITLE
Major Issue - Client Side Crash (server element) while in creative and flying.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ternsip/StructPro#10]
Crashlog
https://gist.github.com/P3rf3ctXZer0/f40d8f479c8800021d0e9f01ebd8af5f

Cursepack
https://www.dropbox.com/s/ziy86wbf6dyvaru/MC-1.10.2-NeverEndingInstability-1.0.zip?dl=0

How to Re-create Crash
Go to world Island Advneture v2 and fly straight for as long as possible. It will crash if you ever fly to a point that has not generated and sky will turn black.

JVM Args
-server -XX:+UseG1GC -Xmx8G -Xms2G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 

Windows Size
1600x900

Pc Specs
Processor	Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz, 3501 Mhz, 4 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM)	20.0 GB
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
System Manufacturer	Gigabyte Technology Co., Ltd.
System Model	Z97X-Gaming 3
System Type	x64-based PC
Name	NVIDIA GeForce GTX 1060 6GB

**Comment by P3rf3ctXZer0** [comment]
[crash-2017-04-18_13.01.03-server.txt](https://github.com/ternsip/StructPro/files/931492/crash-2017-04-18_13.01.03-server.txt)

**Comment by ternsip** [comment]
Done with StructPo 2.7

**Comment by P3rf3ctXZer0** [comment]
Testing now.

**Comment by P3rf3ctXZer0** [comment]
@ternsip this issue has not been fixed ... I can not even make a new world. In the future please don't close an issue till I can confirm it been removed. I am not reporting things to make things harder only to iron out as many bugs as I possibly can.

Error Log
https://gist.github.com/P3rf3ctXZer0/3351751ff910d7b2554e734fcfd5dfaa

**Comment by ternsip** [comment]
First of all - it's other bug. Second - it's bug of BlockDynamicLiquid

**Comment by ternsip** [comment]
It's another bug

**Comment by ternsip** [comment]
You use structpro{2.6} [StructPro] (structpro-2.6-1.10.2.jar)  - it's old version

**Comment by P3rf3ctXZer0** [comment]
![yep](https://cloud.githubusercontent.com/assets/10351221/25246160/6b339ff0-25cc-11e7-8aea-9fac46dab1e5.PNG)

**Comment by ternsip** [comment]
Fully closed because stack-overflow error fixed since 2.7
