### ISSUE TITLE
[1.10.2] Crash on New World Creation

### ISSUE THREAD

**Issue by hextrace** [ternsip/StructPro#11]
**Crash Report:**  https://paste.ee/p/YEYmI
**Forge Version:** *.2554 for MineCraft 1.10.2
**Mod Version:** 2.6-1.10.2

**Description:**  Crash during generating a new world after updating to 2.6 and removing the configuration file in order to incorporate the new changes.

**Potential Conflict:** Given your work on lighting and shadows, OptiFine/Shaders may be interfering.  Will test and update with results.

**Comment by hextrace** [comment]
After a bit of testing I was unable to reproduce the crash.  I even recreated the world using OptiFine/Shaders (including world seed) and the world generated and loaded fine.  That being said, at all stages of my testing I found that 2.6 is definitely taxing my system more than previous versions.  As these are beta releases, these things are to be expected, though.  I'll be reverting back to 2.5 for now.

Not sure if you want to take a deeper look at the ticking error or not; so I'll leave this open for you to close at your discretion.

**Comment by ternsip** [comment]
Dammit this ugly bug are able to appear only when other mod will access world in parallel async thread.
#3841

**Comment by ternsip** [comment]
In StructPro 2.7 You can set TICKER=false to prevent such issues
