### ISSUE TITLE
[MOD = 2.5-2.7][MC = 1.10.2][Server Crash = World Generation Failure]

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ternsip/StructPro#12]
Crashlog
2.7 https://gist.github.com/P3rf3ctXZer0/3351751ff910d7b2554e734fcfd5dfaa
Curse Pack
2.7 https://www.dropbox.com/s/1qwgrey6mhevam4/MC-1.10.2-NeverEndingInstability-1.00001.zip?dl=0

How to Re-create Crash
Go to world Island Advneture v2 and fly straight for as long as possible. It will crash if you ever fly to a point that has not generated and sky will turn black.

JVM Args
-server -XX:+UseG1GC -Xmx8G -Xms2G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

Windows Size
1600x900

Pc Specs
Processor	Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz, 3501 Mhz, 4 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM)	20.0 GB
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
System Manufacturer	Gigabyte Technology Co., Ltd.
System Model	Z97X-Gaming 3
System Type	x64-based PC
Name	NVIDIA GeForce GTX 1060 6GB

Testing 2.7
This issue has not been fixed ... I can not even make a new world. In the future please don't close an issue till I can confirm it been removed. I am not reporting things to make things harder only to iron out as many bugs as I possibly can.
Not resolved this issue intertwined
Anyways some new symptoms ...
No longer plays nice with Recurrent Complex - A mod needed to save backups of structures and import modded structures and schematics. No longer plays nice with BIOMESOP - a mod which has the island generator I need to have island adventures. When structpro is present none of the mods are playing nice.

ModList:
https://cloud.githubusercontent.com/assets/10351221/25246279/c4128a1e-25cc-11e7-8000-3004ab8e9fe1.PNG

**Comment by ternsip** [comment]
Check your structpro version it have to be 2.7

**Comment by P3rf3ctXZer0** [comment]
![yep](https://cloud.githubusercontent.com/assets/10351221/25246142/593e824c-25cc-11e7-9ff9-e2ed0f8e1890.PNG)

**Comment by P3rf3ctXZer0** [comment]
![yep2](https://cloud.githubusercontent.com/assets/10351221/25246212/929462f0-25cc-11e7-83d4-b86eab8b0a75.PNG)

**Comment by P3rf3ctXZer0** [comment]
Anytime a mod author releases anything I update it I have notifications everywhere.
![yep3](https://cloud.githubusercontent.com/assets/10351221/25246279/c4128a1e-25cc-11e7-8000-3004ab8e9fe1.PNG)

**Comment by ternsip** [comment]
Your crashlog https://gist.github.com/P3rf3ctXZer0/3351751ff910d7b2554e734fcfd5dfaa
saying that you have outdated version

**Comment by P3rf3ctXZer0** [comment]
Did you make it with the wrong source? I showed you its 100% up to date I would even let you teamview me as proof.

**Comment by ternsip** [comment]
Yes, I messup with crashlogs in my tabs. Hmm, yes it's a new bug.

**Comment by ternsip** [comment]
biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185931_b(ChunkProviderGenerateBOP.java:537) ~[ChunkProviderGenerateBOP.class:?]
I realize that it's biomes o plenty bug

**Comment by P3rf3ctXZer0** [comment]
Still used to work ... also you could try and explain that to glitchfiend he tends to backport fixes on another modders request but not a users.

**Comment by ternsip** [comment]
Tested and work correctly with:
- BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar
- jei_1.10.2-3.14.7.417.jar
- foamfix-0.6.2-beta4-law.jar
- journeymap-1.10.2-5.4.6.jar
- Mantle-1.10.2-1.1.5.jar
- industrialcraft-2-2.6.27-ex110.jar
- natura-1.10.2-4.1.0.48.jar
- IvToolkit-1.3.2.1-1.10.jar
- RecurrentComplex-1.2.10-1.10.jar

**Comment by ternsip** [comment]
Tested and work correctly with:
- BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar
- jei_1.10.2-3.14.7.417.jar
- foamfix-0.6.2-beta4-law.jar
- journeymap-1.10.2-5.4.6.jar
- Mantle-1.10.2-1.1.5.jar
- industrialcraft-2-2.6.27-ex110.jar
- natura-1.10.2-4.1.0.48.jar
- IvToolkit-1.3.2.1-1.10.jar
- RecurrentComplex-1.2.10-1.10.jar

OptifineHD conflicts with one or several mods from this list
I have to sort issue tracker messages.
