### ISSUE TITLE
[MOD = 2.5][Request = Save Schematics with modded items for Structpro]

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ternsip/StructPro#13]
I would like to stop using reccurrent complex but I need a way to save import and export schematic with a wand. It may help with things if structpro had its own system. It would also make it easier for me to make additional structures. Especially modded structures. I need to be able to export my server hub. Also it would be nice if you added a warning that you have exceeded max structure size if a user tries to save to big an area.

**Comment by ternsip** [comment]
Done with StructPro 3.8
