### ISSUE TITLE
[MOD = 2.8][MC = 1.11.2][Crash = Item check failed]

### ISSUE THREAD

**Issue by POKFX45** [ternsip/StructPro#14]
I got a crash related to, I think, deep resonance:

https://gist.github.com/POKFX45/d560f7c35899991ce893924476c37e9a

I will post it even on DR page

**Comment by ternsip** [comment]
It's mcjty.deepresonance.items.RadiationMonitorItem bug.
But wait for 1.9 version with protection from such things

**Comment by ternsip** [comment]
Have to work since 2.9
