### ISSUE TITLE
[MOD = 2.9][MC  1.10.2][Major Issue = Crash ClientSide Server Module During World Generation]

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ternsip/StructPro#15]
Crash Log
https://gist.github.com/P3rf3ctXZer0/d3f848ff2816ddc1b48b33168f32b9e4

**Comment by P3rf3ctXZer0** [comment]
![9](https://cloud.githubusercontent.com/assets/10351221/25316057/8839c8ee-2825-11e7-8988-529462d5b97f.PNG)

**Comment by ternsip** [comment]
It's a **khorn.terraincontrol** bug
java.lang.NullPointerException: Exception generating new chunk
com.khorn.terraincontrol.generator.biome.LayeredBiomeGenerator.getBiomesUnZoomed
(LayeredBiomeGenerator.java:48)
