### ISSUE TITLE
[MOD = 2.9][MC = 1.10.2][Crash =Ticking Memory Leak Chunk Generation Issues]

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ternsip/StructPro#16]
Crash Log
https://gist.github.com/P3rf3ctXZer0/509b4cdcc4de163c33dd8f7bf58c4acb

**Comment by ternsip** [comment]
I believe it's a foamfix problem, because default minecraft function start calling itself recursively that cause StackOverflowError when number of invested reach stack memory.

**Comment by P3rf3ctXZer0** [comment]
I reported it @Asiekierka

**Comment by asiekierka** [comment]
Did you try to reproduce it without FoamFix?

**Comment by asiekierka** [comment]
@P3rf3ctXZer0 FoamFix Lawful doesn't cause the crash, and FoamFix Lawful does not have a coremod or modify Minecraft code in any significant manner outside of model code which this isn't interacting with.

**Comment by P3rf3ctXZer0** [comment]
It is fixed. I don't know what ternsip fixed but the issue is take care of.

**Comment by ternsip** [comment]
Hmm. I only added height-map calculation. That's really strange because I can't collect a suitable set of mods to reproduce.

**Comment by P3rf3ctXZer0** [comment]
Well that did the trick. You should remember that in the future. Like I said too bug only happened with 1.10.2 so maybe it was needed for 1.10.2 to function correctly.
