### ISSUE TITLE
[2.6] Watching Server Issue

### ISSUE THREAD

**Issue by Alaberti** [ternsip/StructPro#17]
This is on a dedicated server, not sure what to make of it but it lags out the server and crashes it. 
https://pastebin.com/raw/JmQnqDUR

**Comment by ternsip** [comment]
Very important! Go to server.properties and set max-tick-time=-1.
[Read](http://htmlpreview.github.io/?https://raw.githubusercontent.com/ternsip/StructPro/master/web/index.html)
