### ISSUE TITLE
Adding Certain Schematic [question]

### ISSUE THREAD

**Issue by Perkil8n** [ternsip/StructPro#19]
Is there anyway to make sure certain schematics make it in the world? Like just to make sure they're in not particularly in a certain place but just in the world?

**Comment by ternsip** [comment]
use /spro paste name=<schematic name>

**Comment by Perkil8n** [comment]
in cfg?

**Comment by ternsip** [comment]
If you want to check your schematic works you can paste it in the world. Since placing schematic with your name works - you can be sure it will spawn in the world somewhere with some probability.

**Comment by Perkil8n** [comment]
Thank
