### ISSUE TITLE
Major Issue - Newest 1.10.2 Causes Serious Chunk loading issues.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ternsip/StructPro#2]
So basically you cannot make a world with the newest structpro it makes some serious chunk lag occur.

**Comment by ternsip** [comment]
Can you link screenshot or log? It may happens only visually because ADDITIONAL_OUTPUT is false and loading process not showing.

**Comment by P3rf3ctXZer0** [comment]
I think its an issue caused by IC2 and struct pro after removing that mod I no longer suffer the issue. Love your mod by the way nice to see you didn't abandon placemod ;)

**Comment by ternsip** [comment]
I can't solve an issue without any information. Can you please link me your logs?

**Comment by ternsip** [comment]
I tested IC2 also. And it also works. So, I guess the problem is not in IC2 + StructPro. https://ibb.co/dvSh0a

**Comment by P3rf3ctXZer0** [comment]
Not sure then I apologize for wasting our time.

**Comment by ternsip** [comment]
Any way thanks you very much for reporting :)
I welcome all possible bugs and crash-reports.

**Comment by ternsip** [comment]
It fixed long time ago and happened becuase of extended block storage arrays was null
