### ISSUE TITLE
[feature request] a folder called End

### ISSUE THREAD

**Issue by Zygus42** [ternsip/StructPro#20]
Please add a folder called End, all schematics of which will spawn only in the end dimension on end stone.

**Comment by ternsip** [comment]
Do you mean in default schematic pack?

**Comment by Zygus42** [comment]
Yes, but then everything spawns there and looks weird.  I would like stuff that's End-flavoured to spawn in the End, which is quite a dull place really and could use some more content.

**Comment by ternsip** [comment]
You can create "end" folder with your End-flavoured schematics (in subfolder). It will spawn in the end.
