### ISSUE TITLE
[MOD = 3.8][MC = 1.12][Crash  = NoClassDefFoundError]

### ISSUE THREAD

**Issue by Zygus42** [ternsip/StructPro#22]
structpro-3.8-1.12
forge-1.12-14.21.1.2387-installer-win
Tested with no other mods, crashes consistently first time anything tries to get spawned into the world.
[crash-2017-07-03_16.30.33-server.txt](https://github.com/ternsip/StructPro/files/1118912/crash-2017-07-03_16.30.33-server.txt)

**Comment by ternsip** [comment]
Done
