### ISSUE TITLE
[MOD = 3.8][MC = 1.12][Crash  = NoClassDefFoundError]

### ISSUE THREAD

**Issue by Fundryi** [ternsip/StructPro#23]
As the title says, It crashes at startup.

https://gist.github.com/NoplixDE/5ee3f1b12bdb1d0898f9559e036aadb5

**Comment by Zygus42** [comment]
Same issue as #22.

**Comment by MisterObvious25** [comment]
Having the same issue

**Comment by ternsip** [comment]
The link does not working
