### ISSUE TITLE
[MOD = 3.8][MC = 1.12.1][Question = 1.12.1 version works under 1.12]

### ISSUE THREAD

**Issue by MisterObvious25** [ternsip/StructPro#25]
Not sure if it intended but i saw that the bug report that said the 1.12 version didn't work was closed, but now there is only a 1.12.1 version available and no longer a 1.12 version is this intended?

Maybe make the 1.12.1 version work on both 1.12 and 1.12.1.

**Comment by ternsip** [comment]
Yes, 1.12.1 works on 1.12 also

**Comment by MisterObvious25** [comment]
It does not, that is why i was confused. just checked it again

**Comment by ternsip** [comment]
Done - fixed. Thank you very much. I really appreciate.
