### ISSUE TITLE
[MOD = 4.0][MC = 1.12.1] [Commands don't take arguments] 

### ISSUE THREAD

**Issue by AfterRebelion** [ternsip/StructPro#27]
Structures generate fine, but the /spro paste and gen commands ignore arguments, so a can't gen/paste especific schematics, it only generates random ones.
I tried every combination I could think off: [Author]StructureName.schematic , [Author]StructureName , StructureName.schematic , StructureName and none seemed to work.

As a note, I changed the default folder to SCHEMATIC_FOLDER=config\\schematics

**Comment by Came1ot** [comment]
First of all generation process (/spro gen) takes arguments only the following: generation radius measured in chunks, starting chunk position, amount of chunks processed per tick, skip chunks that don't contain mod structures or not, start generation progress from some value, world to pre-generate. And it doesn't require structures name, it's just world common/basic generation with spawning structures using their default position in the world (depends on world seed and block environment where it trying to spawn).
Secondly, if you want to spawn StructureName.schematic (such file in your config/schematics)
just use **/spro paste name=StructureName**
And its enough.
I just tested, everything works fine.

**Comment by AfterRebelion** [comment]
Yes, my bad, for some reason skipped that part of the doc, so  I didn't add the name tag.
You can close this.
