### ISSUE TITLE
[Website] Information page not working.

### ISSUE THREAD

**Issue by ElvenChaos** [ternsip/StructPro#29]
When trying to view the [documentation](http://htmlpreview.github.io/?https://raw.githubusercontent.com/ternsip/StructPro/master/web/index.html) page, getting a white screen with "No definition found for Table headers."

I've tried the link from both curseforge and from github, and I've tried using both firefox and chrome.

EDIT: Documentation site decided to work again 30~60 min later, and I have no idea why. Fixed? Leaving this here and open in case any other instances of this issue occur for anyone else, and to document that there _was_ a problem.

**Comment by ternsip** [comment]
Now using rawgit, here's the [link](https://rawgit.com/ternsip/StructPro/master/web/index.html)
