### ISSUE TITLE
Crash while Loading Chunks

### ISSUE THREAD

**Issue by WenXin20** [ternsip/StructPro#3]
Structpro v1.2
Forge 2254-1.10.2
I get this crash while generating new chunks in my world. The crash log mentions a lot of other mods that seem the be related to world generation as well.
[Crash Report](https://pastebin.com/EdjkVu5R)

**Comment by ternsip** [comment]
Ahh. I see now. Wait for fix in version 1.3. I I bet on CoreMod chunk popualting system. It Reduces сhunk storages that cause this problem. =)

**Comment by WenXin20** [comment]
Ok, thank you. :)

**Comment by ternsip** [comment]
Please check 1.3 version
