### ISSUE TITLE
[Suggestion] Add a UI for Schematic Pasting 

### ISSUE THREAD

**Issue by MokahTGS** [ternsip/StructPro#4]
Adding a UI for schematic pasting into a world would be huge.  Schematica has a way of seeing a ghost image of a schematic in the world and move it around with a UI which is really helpful for placing builds EXACTLY where you need them to go.  The only issue is Schematica doesn't have a paste function.  You can build it block by block...but not paste.

I know it can be done with commands but if you somehow get it wrong your screwed.  A UI with a preview ghost of the schematic would make this a really great tool.

**Comment by P3rf3ctXZer0** [comment]
yeah then recurrent complex would no longer be needed

**Comment by ternsip** [comment]
Schematica mod have UI that draws schematic ghost. My mod can **paste** | **save** structres or villages.
And now there is possibility to **undo** last action. So I don't see any origins to do that.
