### ISSUE TITLE
Request - Curse Changelogs 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ternsip/StructPro#5]
I am one of the few people who care about change-logs due to a lot of testing I do. Can you please start adding a small paragraph of the change made per release? Example : version X fixed a crash when chunkloading took place during certain mods interactions.

**Comment by ternsip** [comment]
Yes, I'll do it. Is it works now for you in version 1.3?

**Comment by P3rf3ctXZer0** [comment]
I have not tested it yet.
