### ISSUE TITLE
Major Issues - Spawning Break 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ternsip/StructPro#6]
https://minecraft.curseforge.com/projects/structpro-mod-fast-schematic-spawning-system/files/2401444
![2017-03-27_08 43 03](https://cloud.githubusercontent.com/assets/10351221/24586727/1227e3d4-176d-11e7-9277-0c6985e54d64.png)
![2017-04-02_06 22 09](https://cloud.githubusercontent.com/assets/10351221/24586726/122746a4-176d-11e7-889c-898c52d4ad6f.png)
![2017-04-02_06 22 58](https://cloud.githubusercontent.com/assets/10351221/24586728/122bfa64-176d-11e7-93a1-2696accbe288.png)
![2017-04-02_06 23 03](https://cloud.githubusercontent.com/assets/10351221/24586730/122c7d68-176d-11e7-8b41-deeb3a137a2a.png)
![2017-04-02_06 23 07](https://cloud.githubusercontent.com/assets/10351221/24586731/122d281c-176d-11e7-96cb-862d62a79344.png)
![2017-04-02_06 23 14](https://cloud.githubusercontent.com/assets/10351221/24586729/122c1102-176d-11e7-9b41-de7e091a569a.png)
![2017-04-02_06 23 47](https://cloud.githubusercontent.com/assets/10351221/24586732/12341000-176d-11e7-9e86-a56023486d87.png)
![2017-04-02_06 23 52](https://cloud.githubusercontent.com/assets/10351221/24586733/12371598-176d-11e7-9470-6f1e810ede23.png)

**Comment by ternsip** [comment]
Wow, thats not good and it's hard to reproduce. Maybe you have some extra information?

**Comment by ternsip** [comment]
Remove your sprodump folder

**Comment by P3rf3ctXZer0** [comment]
no its actually in the world. I will remove the dump files.

**Comment by P3rf3ctXZer0** [comment]
I am not done testing this.

**Comment by ternsip** [comment]
Can't reproduce. But I've got it one time in 1.7 version, so it still opened. Thank you.

**Comment by P3rf3ctXZer0** [comment]
Okay so I am finding serious world generation bugs ... can you help figure this out?

**Comment by P3rf3ctXZer0** [comment]
@ternsip I am checking with other mod authors as well people who mess with world generation code.
https://github.com/fewizz/NotEnoughIDs/issues/58

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/980

**Comment by ternsip** [comment]
**sprodump** folder contains schematics flags and it skinning so it may produce some torny chaos, but not like that it's chunk-generation problems.

**Comment by ternsip** [comment]
It's not because of **sprodump** folder

**Comment by P3rf3ctXZer0** [comment]
Okay @ternsip I can confirm its serverside issues only. Please double check server chunk generation code.
