### ISSUE TITLE
[1.10.2] Blank Config 2.4.1.10.2

### ISSUE THREAD

**Issue by MokahTGS** [ternsip/StructPro#8]
I updated and now my config is blank.  Any idea how to get it back or what are the default values?

**Comment by ternsip** [comment]
When you start minecraft it automatically rewrites and fix all problems

**Comment by MokahTGS** [comment]
still blank...

**Comment by MokahTGS** [comment]
Can I leave the dimension white lists blank if I do not want any structure generation and am just using this as a utility?

**Comment by MokahTGS** [comment]
Nope...config is blank again.  I deleted it and restarted the world to generate a new config.  It did this, and then I closed out and made my changes to the config.  Restarted again and now the config is blank.

**Comment by ternsip** [comment]
Yes, you can use it blank of course. If it not works its a bug.

**Comment by ternsip** [comment]
I realize problem wait for 2.5 version

**Comment by ternsip** [comment]
Done with https://github.com/ternsip/StructPro/commit/d305544542b32470e2da55d08bc66da7585e0d30
