### ISSUE TITLE
[MOD = 1.5-2.7][MC = 1.10.2][Spawn Abrupt = Serverside Only Issues with Generation]

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ternsip/StructPro#9]
This issues do not exist client-side period. They do not exist on lan either. Having server generation issues you could always ask @Ivorforce for help. He hit a snag like this back on 1.7.10.
https://github.com/ternsip/StructPro/issues/6
fewizz/NotEnoughIDs#58
Ivorforce/RecurrentComplex#176
Glitchfiend/BiomesOPlenty#980

**Comment by ternsip** [comment]
Tested and work correctly with:
- BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar
- jei_1.10.2-3.14.7.417.jar
- foamfix-0.6.2-beta4-law.jar
- journeymap-1.10.2-5.4.6.jar
- Mantle-1.10.2-1.1.5.jar
- industrialcraft-2-2.6.27-ex110.jar
- natura-1.10.2-4.1.0.48.jar
- IvToolkit-1.3.2.1-1.10.jar
- RecurrentComplex-1.2.10-1.10.jar
